### ISSUE TITLE
Look into reducing number of fonts and font requests

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#174]
See: https://github.com/Automattic/abacus/pull/170#discussion_r446721787

Low priority for now as we're still developing the app.

**Comment by dhurlburtusa** [comment]
Since I ran across related information yesterday, I thought I would share.

Currently, one of the font files we import via a `link` tag is for the MUI Icon fonts. This is one way to use icons in MUI and MaterialTable. Another way is using the `@material-ui/icons` package. These two solutions are a trade-off -- 1 less request for a larger bundle. In my experience, a change like this makes no noticeable difference to any end-users.

Here are the links to related info:
- https://material-ui.com/components/icons/
- https://material-table.com/#/docs/install

**Comment by jessie-ross** [comment]
Can we close this as unnecessary?

**Comment by yanirs** [comment]
Yeah, I don't mind closing for now.
