### ISSUE TITLE
Verify that all the pages are mobile friendly

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#176]
As discussed in https://github.com/Automattic/abacus/pull/169#issuecomment-651170615, we're going for a "desktop first, mobile second" approach, i.e., a great experience on desktop/tablet and passable usability on mobile. This means that the pages should render nicely on mobile, but not necessarily be optimised for narrow screens. Right now, not all pages are very usable, e.g., some tables require horizontal scrolling. We should do a pass through the main views and tweak things as needed.

**Comment by aaronyan** [comment]
Just tried this out, and it's pretty straightforward. Here's the [FG page](PCYsg-5yJ-p2) and an overview:

1. Create [VPN credentials](https://mc.a8c.com/vpn/)
2. Email yourself the credentials (OpenVPN one, not Tunnelblick)
3. Download the OpenVPN app
4. Download the emailed credentials
5. Import the credentials into the app ([iOS](PCYsg-5yJ-p2#ios-openvpn), [Android](PCYsg-5yJ-p2#android))
6. Connect to the VPN
7. Visit https://experiments.a8c.com/

**Comment by aaronyan** [comment]
For instructions on how to access Abacus on mobile, checkout the guide to setting up a VPN in [our wiki](https://github.com/Automattic/experimentation-platform/wiki/ExPlat-developer-resources#setting-up-vpn-to-access-abacus-on-mobile)! :)

**Comment by jessie-ross** [comment]
I've gone through the pages assessing responsiveness via device emulation using standard browser dev tools:
- **Experiment List**: Fully functional to mobile.
- **Experiment Wizard**: With #575, a decent experience for tablet, just have to scroll a little on the metrics page, but very usable. 
- **Experiment Overview**: Looks good on tablet. Functional on mobile.
- **Experiment Results**: Looks good on tablet, have to scroll a little for metric results but I'd say this is within usual tablet experience. Functional on mobile. In order to improve things for tablets we would need to switch away from using grids into more like a series of cards.

All up, with #575, I call this "Great experience" for tablet, and passable functionality for mobile.

**Comment by yanirs** [comment]
Thanks @jessie-ross!

Sort of related: There are several places with view overflows even on wide displays. I tested by adding an experiment and metric named `explat_test_very_long_name_yes_this_name_is_very_long_and_it_still_fits_within_our_limits_will_it_look_good_though_who_knows`. With this:

* Experiment List looks good
* Experiment Overview has several overflows
* Metric List overflows

Can you please look into it? We can also split this into a separate issue since it's a general overflow problem.

**Comment by jessie-ross** [comment]
> Can you please look into it? We can also split this into a separate issue since it's a general overflow problem.

I've split it into https://github.com/Automattic/abacus/issues/578

Looks like this issue should be resolved by #575
