### ISSUE TITLE
Multiply conversion metric units by 100

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#377]
**Q: Should we adjust the conversion metric units to "points" (from "pp")?**

Right now, we use `pp` to define "percentage points" for conversion metrics. We primarily use this unit when talking about the minimum difference value.

**Q: Should we multiple the conversion metric units by 100?**

The conversion metric units are also unchanged and a `0.02` value will appear as `0.02 pp`. I think we should be displaying this value as `2 pp`, which is basically x100 the original value. When reading metric assignments, we would x100. And when writing metric assignments, we would /100 before sending the request. 

Background to this issue: creating the experiments in Abacus for the monthly pricing experiment, and it got my thinking about this conversion metric unit experience.

## Action items

- [x] Discuss if we want to adjust conversion metric units from `pp` to `points`
- [x] Discuss if we want to multiply the values by 100 to show `2 points` instead of `0.02 points` (The actual value is 2/100).
- [x] Implement any of the changes discussed above

**Comment by yanirs** [comment]
> Q: Should we adjust the conversion metric units to "points" (from "pp")?

In my opinion, we should stick to "pp" or spell it out, as "points"  is ambiguous and not commonly used. See https://en.wikipedia.org/wiki/Percentage_point.

> Q: Should we multiple the conversion metric units by 100?

Yeah, that's a good point (ha!). The UI should be consistent and unambiguous, and we already multiply the value when displaying the ROPE, so it makes sense to applying the multiplications to displaying and entering the metric assignment values.

**Comment by aaronyan** [comment]
> In my opinion, we should stick to "pp" or spell it out, as "points" is ambiguous and not commonly used

Yeah, "points" is not too common. It is sometimes used in [finance and elections](https://en.wikipedia.org/wiki/Point). But generally, "points" is more vague and easier to misunderstand than our "pp" abbreviation.

Maybe we should add a tooltip saying "percentage points" when hovering over "pp"?

**Comment by aaronyan** [comment]
The only remaining action item for this is to multiply the conversion metric units by 100. We will need to be careful of dividing by 100 when in the UI -> database. And then multiplying by 100 when reading from the database -> UI. Adjusted the title of the issue to reflect the remaining issue.

**Comment by jessie-ross** [comment]
> The conversion metric units are also unchanged and a 0.02 value will appear as 0.02 pp. I think we should be displaying this value as 2 pp, which is basically x100 the original value. When reading metric assignments, we would x100. And when writing metric assignments, we would /100 before sending the request.

I have been thinking about this and come to this conclusion: Percentage points are an absolute difference not a relative difference like percentage - they shouldn't be scaled. 

Current:



Raw without any scaling:

<img width="1136" alt="Screen Shot 2021-01-12 at 12 44 41 pm" src="https://user-images.githubusercontent.com/971886/104270703-10684180-54d4-11eb-91c7-b4f132a2e3fb.png">

- Currently we scale diff estimates up - this is fine as they are difference of ratios. 
- We scale ROPE up, this is where the problem and confusion lies - they are already percentage points.

I think all we need to do is descale ROPE to make everything make sense, #435:

<img width="1137" alt="Screen Shot 2021-01-12 at 12 52 59 pm" src="https://user-images.githubusercontent.com/971886/104271246-5e317980-54d5-11eb-9bf5-fd31560ac4dd.png">

I think the confusion about the pp in this issue comes from ROPE being scaled up accidentally.

Closing this issue in favour of #435, feel free to reopen.

**Comment by jessie-ross** [comment]
Ah looks like we can fix the scaling in the CI outside the graph too.

**Comment by yanirs** [comment]
Hmm... I think that the problem may be that the behaviour in Abacus doesn't match the backend. The ETL assumes (but doesn't check) that the `min_difference` is between 0 and 1 for conversion metrics, but by specifying `pp` on the front-end, humans assume that it's between 0 and 100. To match what the backend expects, we should scale the `min_difference` by dividing by 100 on input and then multiplying by 100 on output.
