### ISSUE TITLE
Deploy master to experiments.a8c.com

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#42]
Before we launch Abacus, we should map get the production server from `master` to run on `experiments.a8c.com` (requires an internal Systems request).

**Comment by aaronyan** [comment]
Drafted an [internal systems request](https://systemsrequests.wordpress.com/?p=43832)! Feel free to adjust to include any additional details I may have missed.

Started this because Martin had a few questions about security. We did some research, and wanted to document it here since it would probably be useful for the systems request.

**Comment by yanirs** [comment]
Systems request published following a draft by @aaronyan and tweaks by me. Let's see how it goes...

**Comment by yanirs** [comment]
Update: We'll be running `master` on an internal server. This requires a Dockerfile, which is coming soon.

**Comment by yanirs** [comment]
This is done! The production host is accessible using our VPN or proxy.
