### ISSUE TITLE
Prevent horizontal scrolling on experiment results and metric directory

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#677]
Let's prevent horizontal scroll in all the places:
- [x] Experiment results view
- [ ] Metrics directory (https://github.com/Automattic/abacus/pull/735)

When viewing results of an experiment, long metric names cause the results to horizontal scroll. Let's remove that (and any other areas we can think of)! Example experiment `20365` and an accompanying screenshot:

<img width="1290" alt="Screen Shot 2022-04-28 at 12 00 26 PM" src="https://user-images.githubusercontent.com/4505888/165827575-b2d00fad-bf4a-4b93-bfdb-9d9b7af1eae3.png">

**Comment by aaronyan** [comment]
One way of preventing horizontal scroll is by having a character limit on the metric name and postfixing with "..." if the metric name reaches the limit. And then allowing the full name to be viewed on hover.

**Comment by razvanpapadopol** [comment]
Hey, @aaronyan! I fully agree this is annoying and it should be fixed soonish. It may even be considered a bug since just adding a single metric with a lengthy name, the "scroll of doom" is introduced 😅 

I've done a bit of exploration on this topic in the context of https://github.com/Automattic/abacus/pull/675 and this is what I could prototype:
<img width="1284" alt="Screenshot 2022-05-25 at 00 18 39" src="https://user-images.githubusercontent.com/14192054/170134887-e5cde024-11ed-405e-a7c3-957bab2df124.png">

A few advantages of the solution above: 
- it involves just a tiny set of changes (only CSS to break the metric name and add a max-width of 450px to its column) so we may release the fix and iterate
- the full metric name continues to be visible and available to copy immediately (eg: double click to select)
- with the CI diagrams we increase the height of the rows anyway so a metric on two lines would still fit nicely

> having a character limit on the metric name and postfixing with "..." if the metric name reaches the limit.

It would be nice indeed as we're doing this already with the experiment name and also in the Metrics table on the Overview page.

> And then allowing the full name to be viewed on hover.

We currently render the description there but we could probably move it on a separate tooltip (maybe follow the pattern with the Info icon in https://github.com/Automattic/abacus/pull/699?). Also, it's pretty impossible to copy from a tooltip so we may want to include the full metric name again in the Detail Panel below.

**Comment by aaronyan** [comment]
> adding a single metric with a lengthy name, the "scroll of doom" is introduced

That looks awesome! I am totally down for wrapping text when there's overflow. :) Easy to iterate too! And in the meantime, the "scroll of doom" will be gone 😄 

> We currently render the description there but we could probably move it on a separate tooltip (maybe follow the pattern with the Info icon in https://github.com/Automattic/abacus/pull/699?). Also, it's pretty impossible to copy from a tooltip so we may want to include the full metric name again in the Detail Panel below.

That's a good point. Yeah, showing the full name somewhere will be important for copy/paste.

**Comment by razvanpapadopol** [comment]
Thanks for the quick feedback, @aaronyan ! I've PR'ed the proposed CSS change together with all the necessary testing in https://github.com/Automattic/abacus/pull/714
 
Now if we're here, I suggest we continue for other screens as well. For example, see the 4th page in Metrics Directory 🙈

**Comment by aaronyan** [comment]
Adjusting the metrics directory to also not have horizontal scroll sounds great to me, @razvanpapadopol! Adjusting the issue title and description to reflect that!
