### ISSUE TITLE
Disable assign metric for disabled experiments

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#711]
It looks like metrics can be assigned to disabled experiments (pbxNRc-1qR-p2#comment-3368)! I forgot why we allow this, but I guess it doesn't hurt to keep as long it's not being abused. I think we should disable the "assign metric" button once the experiment has finished collecting data. We can attach metrics to really old experiments (and it won't do anything).

An experiment is defined as finished collecting data when the current date is past the largest analysis end date. For each assigned metric, we calculate the [analysis end date](https://github.com/Automattic/nosara/blob/beecb752bdea430a3cfddb453101693ca6f278e5/airflow/ganymedes/sqlt/src/main/resources/sql/experiments/metric_assignments_to_analyze.sql#L16-L20):

- end date + longest attribution window + refund window + 1 day

What are your thoughts? 

- Should we allow disabled experiments add metrics?
- Should we disable assign metric after a certain period of time?

**Comment by jessie-ross** [comment]
Because we backfill for 14 days (or more manually) this can be useful after the experiment has ended.

We could probably add a line in here:

<img width="1261" alt="Screen Shot 2022-05-25 at 12 03 14 pm" src="https://user-images.githubusercontent.com/971886/170177216-3b271650-119c-4e8b-bfe9-a74825881cc1.png">

Saying something like

`If the metric was added recently and the experiment is over 14 days old it may need to be manually backfilled (Contact ExPlat)`


> We can attach metrics to really old experiments (and it won't do anything).

If we backfill we can add metrics and get the analyses from as old as we have data for - e.g. only limited by retention policies.

**Comment by razvanpapadopol** [comment]
If there is no technical limitation, I'd say we should continue to allow adding metrics to old experiments (as the retention policies allow). When designing a new experiment, there are, in many cases, references to previous related experiments. If they are missing a certain metric of interest (not necessarily a recently added one), it could be helpful to have the option to get its analysis in order to see the big picture before setting up the new experiment.

**Comment by aaronyan** [comment]
Sounds good to me to continue allowing metrics to be added to disabled experiments. I like the idea of adding a line to the no analysis data found section as a quick solution to inform experimenters why no data is being calculated.

I'm not the biggest fan of providing manual backfills, but we can allow it for now and see what the demand is like. :)

**Comment by aaronyan** [comment]
Closing this issue and creating a [new issue](https://github.com/Automattic/abacus/issues/715) to represent the new direction of adding a line to the "no analysis data found" section!
