### ISSUE TITLE
Fix assignment bookmarklet CORS error

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#727]
Experimenters are seeing a CORS error when they attempt to assign themselves an experiment variation in Abacus using the bookmarklet (p1654179042089569-slack-C7HH3V5AS). It gets resolved when sandboxing the API (p1654517167700969-slack-C7HH3V5AS), but we should fix it so experimenters don't have to jump through hoops to test their experiment. It may be coincidence, but this issue seems to have come up when Barry made a few changes to the API:

- Prevent cache stampede (pMz3w-fi5-p2#comment-98861)
- Rate limiting API (pMz3w-fi5-p2#comment-98875)

**Comment by jessie-ross** [comment]
Hmm, I can't quite see why it would be caused by Barry's changes. I feel like it might be something else that's changed. I do feel like we may have always required sandbox to perform manual assignment? cc @withinboredom

The CORS issue is also fixed when the bookmarklet is run off of a *.wordpress.com domain, so the solution here might just be as simple as adding an extra line to the instructions in, perhaps in bold.

**Comment by withinboredom** [comment]
Sandbox wasn't always required. But it might be a CORs issue if the domain they are running the bookmarklet on isn't explicitly whitelisted in the API code.

**Comment by aaronyan** [comment]
I think it's important to be able to call the bookmarklet from Abacus. What does it take to explicitly whitelist experiments.a8c.com in the API code?
