### ISSUE TITLE
Disable assignment distribution health report for `mlsales` experiments

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#786]
Now that `mlsales` experiments have been moved to their own platform, let's disable the assignment distribution health report calculation. These experiments will manually assign users to assignment groups, so they will likely not match up to the specified assignment ratio specified in the experiment model.

This issue replaces solves the problem of https://github.com/Automattic/abacus/issues/750.

**Comment by razvanpapadopol** [comment]
Hey, @aaronyan, it's great to see that `mlsales` experiment have their own platform now!

I know this wasn't part of the current milestone (pbmo2S-1EV-p2) but since the change was already drafted in https://github.com/Automattic/abacus/pull/751, it just needed the latest changes and replaced platform "Email" with "Mlsales" 🎉
