### ISSUE TITLE
Add experiment creation page

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#9]
Aaron wrote: For experiment creation, let's follow the design created by Kelly in the design request! A three step process:

- New experiment - gate the creation with a P2 url
- Experiment creation - three sections: basic info, audience, user details
- Success page - include a static code snippet (we can help create those for you)

**Comment by aaronyan** [comment]
From our project call, we decided that we'll prioritize _view pages_ over _creation pages_. This means that for the experiment creation page, we'll break this issue up into smaller fragments so that way we can merge what we currently have, and then work on completing the rest of the experiment creation flow later.

Here's how I envision breaking up the current experiment creation flow into checkpoints (headers) and fragments (checkboxes):

### 1. Base experiment
- [ ] New experiment landing page
- [ ] Basic Info page
- [ ] Audience page (with _variations_ moved here, segmentation not required)
- [ ] Metrics page (with empty assigned metrics)
- [ ] Code snippets page

### 2. with existing metrics/segments
- [ ] Add existing segmentation selection to Audience page
- [ ] Add existing metric selection to Metrics page 

### 3. with custom metric
- [ ] Add custom metric creation and selection to Metrics page

Checkpoints don't have to be fully complete in order to move on to higher priority items (it's just a rough guide). We do recommend merging a fragment (checkbox) if significant work has been started on it before moving on to something else.

**Comment by aaronyan** [comment]
>New experiment landing page
 Basic Info section
 Audience section (with variations moved here, segmentation not required)
 Metrics section (with empty assigned metrics)

There is a slight discrepancy between what is checked and what is committed in the WIP PRs. These PRs have the different sections but @dhurlburtusa removed the layout code that allows you to navigate between the sections. This was done to make it easier for comparison. Dan has the layout code done, but it is saved off and is ready to be integrated into whichever implementation we chose.

**Comment by aaronyan** [comment]
> Success page - include a static code snippet (we can help create those for you)

@withinboredom, what does the assignment code snippet look like for `calypso` and `wpcom`? I found an [example of a Calypso code snippet](https://github.com/Automattic/wp-calypso/blob/04ac348d1f477f897409da457b7a9ca6db1b4402/client/my-sites/customer-home/main.jsx#L82-L91) in action! What kind of comments should we add to the snippet to make it easy for folks to use. Looks like the three main fields that we'll replace from data collected during experiment creation are:
- `<Experiment name="___experiment_name_here___">`
- `<DefaultVariation name="___default_variation_name_here___">`
- `<Variation name="___other_variation_name_here___">`

**Comment by aaronyan** [comment]
Documenting some minor changes that I think we should consider when building out the creation:
- Hehe I changed my mind again @dhurlburtusa, let's keep the collapsing the way it was designed and keep the next button, but align the next buttons to the right.
- Perform form checks on each next button click
- `+Add segmentation` should be a button
- All `Add` or `Assign` buttons should have a `+` icon left of the text (but inside button) - see our internal mockups for `+ add experiment`

I'll edit this comment and add *updates if I see anything else!

**Comment by yanirs** [comment]
Closing this as it's already done and any leftovers/tweaks should be handled as separate issues.
